### ISSUE TITLE
Wordpress 4.5.2 update issue

### ISSUE THREAD

**Issue by iamlenox** [technomile/Heroku-WordPress#5]
When going through the wordpress update buttons in wp-admin it loops back to the Thanks for updating to 4.4.2 and refuses to update to 4.5.2 ... any fix for this?

**Comment by InderjeetSohal** [comment]
Heroku supports read only file system and does not allow to write any files. You will have to git pull your app repository and then git push with updated WordPress version.

**Comment by InderjeetSohal** [comment]
Today we have upgraded WordPress 4.5.2 and all the plugins are also updated. You can reinstall WordPress again from our build pack.

**Comment by iamlenox** [comment]
This is great news!
