### ISSUE TITLE
Cannot install Collective theme => Voulez-vous vraiment faire cela ?

### ISSUE THREAD

**Issue by Guillaumejfrt** [technomile/Heroku-WordPress#8]
Hi,

I am facing a error when I want to install my theme through the 'Appearance -> Themes' menu.

My theme is Collective (https://themeforest.net/item/collective-minimal-wordpress-theme/16956348)

Can you help me?

Thanks a lot

**Comment by Guillaumejfrt** [comment]
sorry I found my mistake

**Comment by Chloelepez** [comment]
Can you tell me what you did?

**Comment by Guillaumejfrt** [comment]
hello @Chloelepez ,

sorry but that was 6 month ago. I don't even remember. I finally used an instance on Gandi to host my Wordpress site.
